//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public string Code { get; set; }
        public string BankName { get; set; }
        public string IBAN { get; set; }
        public string BalanceAssets { get; set; }
        public string BalanceLiabilities { get; set; }
    }
}
