//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensePaymentRefound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpensePaymentRefound()
        {
            this.GLExpensePaymentRefound = new HashSet<GLExpensePaymentRefound>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string GLAccountCode { get; set; }
        public Nullable<int> PeopleId { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public byte Status { get; set; }
    
        public virtual GLAccount GLAccount { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLExpensePaymentRefound> GLExpensePaymentRefound { get; set; }
    }
}
