//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLExpensePaymentRefound
    {
        public long GLExpensePaymentRefoundId { get; set; }
        public long ExpensePaymentRefoundId { get; set; }
        public long GeneralJournalLineId { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ExpensePaymentRefound ExpensePaymentRefound { get; set; }
        public virtual GeneralJournalLines GeneralJournalLines { get; set; }
    }
}
