//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobBalance
    {
        public long JobBalanceId { get; set; }
        public long JobId { get; set; }
        public string GLAccountCode { get; set; }
        public decimal Amount { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual GLAccount GLAccount { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual DocumentType DocumentType1 { get; set; }
    }
}
