//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobBusinessGroup
    {
        public string JobBudgetBusinessGroupId { get; set; }
        public string Invoice { get; set; }
        public string TravelExpense { get; set; }
        public string OtherCosts { get; set; }
        public string Works { get; set; }
    }
}
