//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCosts
    {
        public int JobCostId { get; set; }
        public long JobId { get; set; }
        public string GLAccountCode { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
    
        public virtual GLAccount GLAccount { get; set; }
        public virtual Jobs Jobs { get; set; }
    }
}
