//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExpected
    {
        public long JobId { get; set; }
        public Nullable<decimal> ExpectedIncome { get; set; }
        public Nullable<decimal> ExpectedCost { get; set; }
        public Nullable<int> ExpectedWorks { get; set; }
    }
}
