//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTravelExpenseList
    {
        public long JobId { get; set; }
        public string TravelExpenseCode { get; set; }
        public short Percent { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> TravelExpenseTotal { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> PeopleId { get; set; }
    }
}
