//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBusinessAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonBusinessAccount()
        {
            this.Person = new HashSet<Person>();
        }
    
        public string Code { get; set; }
        public string DebitAccountCode { get; set; }
        public string CreditAccountCode { get; set; }
        public string TravelExpenseAccountCode { get; set; }
        public string TravelExpenseInvoiceAccountCode { get; set; }
        public string CompensoAccountCode { get; set; }
        public string TaxAccountCode { get; set; }
        public string InpsAccountCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person { get; set; }
    }
}
