//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePaymentRefound
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string GLAccountCode { get; set; }
        public int PeopleId { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public byte Status { get; set; }
    
        public virtual GLAccount GLAccount { get; set; }
        public virtual Person Person { get; set; }
    }
}
