//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseList
    {
        public string TravelExpenseCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Annotation { get; set; }
        public byte Status { get; set; }
        public Nullable<int> PeopleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
    }
}
