//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCosts
    {
        public long JobCostId { get; set; }
        public long JobId { get; set; }
        public string Type { get; set; }
        public string TravelExpenseCode { get; set; }
        public Nullable<long> PurchaseInvoiceId { get; set; }
        public Nullable<short> Percent { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
