//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.WorksJournal = new HashSet<WorksJournal>();
            this.TravelExpenseJobs = new HashSet<TravelExpenseJobs>();
        }
    
        public long JobId { get; set; }
        public long CustomerId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public decimal ExpectedIncome { get; set; }
        public decimal ExpectedCost { get; set; }
        public int ExpectedWorkHours { get; set; }
        public byte Status { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public Nullable<System.DateTime> ExpectedFinishDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual JobStatus JobStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksJournal> WorksJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpenseJobs> TravelExpenseJobs { get; set; }
    }
}
