//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.WorksJournal = new HashSet<WorksJournal>();
            this.TravelExpenses = new HashSet<TravelExpenses>();
        }
    
        public int PeopleId { get; set; }
        public string IdentityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public byte Contract { get; set; }
        public string Email { get; set; }
        public decimal HourCost { get; set; }
        public bool ActiveState { get; set; }
        public string Code { get; set; }
        public string CarPlate { get; set; }
        public string CarDescription { get; set; }
        public decimal CarKmCost { get; set; }
        public bool IdentityDefault { get; set; }
        public string DebitAccount { get; set; }
        public string CreditAccount { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksJournal> WorksJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpenses> TravelExpenses { get; set; }
    }
}
