//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchases()
        {
            this.TravelExpensePurchases = new HashSet<TravelExpensePurchases>();
        }
    
        public long PurchaseId { get; set; }
        public string BuyFromName { get; set; }
        public string BuyFromCity { get; set; }
        public string BuyFromCountry { get; set; }
        public Nullable<int> BuyFromDocType { get; set; }
        public string BuyFromDocNumber { get; set; }
        public Nullable<System.DateTime> BuyFromDocDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountNoVat { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpensePurchases> TravelExpensePurchases { get; set; }
    }
}
