//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoices
    {
        public long PurchaseInvoiceId { get; set; }
        public string BuyFromName { get; set; }
        public string BuyFromCity { get; set; }
        public string BuyFromCountry { get; set; }
        public Nullable<int> BuyFromDocType { get; set; }
        public string BuyFromDocNumber { get; set; }
        public Nullable<System.DateTime> BuyFromDocDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountNoVat { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string GLAccountCode { get; set; }
        public int WhoPayId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    }
}
