//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseAutoCode
    {
        public int PeopleId { get; set; }
        public int Year { get; set; }
        public string Prefix { get; set; }
        public int LastUsedNumber { get; set; }
    }
}
