//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksJournal
    {
        public long WorkJournalId { get; set; }
        public long JobId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal WorkedHours { get; set; }
        public string TaskWhere { get; set; }
        public string Annotation { get; set; }
        public string JobTaskId { get; set; }
        public int PeopleId { get; set; }
    
        public virtual Jobs Jobs { get; set; }
        public virtual JobTasks JobTasks { get; set; }
        public virtual Person Person { get; set; }
    }
}
