//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.EFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseJobsList
    {
        public string TravelExpenseCode { get; set; }
        public long JobId { get; set; }
        public decimal InPercent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}
